(#2) Create initial workflow template
NCIOCPL/.github pull request #3
Opened 2022-07-29 12:13 UTC by jfrank-nih

Closes #2

2022-08-18 17:31 UTC, bryanpizzillo requested changes

2022-09-14 15:51 UTC, bryanpizzillo requested changes

2022-09-14 15:51 UTC, bryanpizzillo commented on workflow-templates/ocpl_cm_standards_check.yml
> +    uses: NCIOCPL/.github/workflows/ocpl_cm_standards_check.yml@workflows-v1
Also this path is wrong. you are missing a `.github`. In the path. (I know, I just tried it on cgov-digital-platform)

2025-10-07 17:19 UTC, jfrank-nih commented
Closing out. This is outdated.

2025-10-07 17:19 UTC, closed without merging